# Generated by Django 4.2.18 on 2025-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
